In [1]:
import numpy as np
d1 = np.array([1,2,3,4,5])                                                      # tablica jednowymiarowa - lista elementow zamknieta w []
d2 = np.array([[1,2,3,4,5], [2,3,4,5,6]])                                       # tablica dwuwymiarowa - lista elementow ktore sa tablicami jednowymiarowymi i to wszystko zamkniete w []
d3 = np.array([[[1,2,3,4,5], [6,2,3,4,5]], [[7,2,3,4,5], [8,2,3,4,5]]])         # tablica trzywymiarowa - lista elementow ktore sa tablicami dwuwymiarowymi i to wszystko zamkniete w []
                                                                                # w tablicy 3 wymiarowej mamy shape w postaci depth x rows x columns
print(type(d1))
print(type(d2))
print(type(d3))

print(d1.shape)
print(d2.shape)
print(f"{d3.shape}, \n")

print(f"{d1}, tablica 1wymiarowa\n")
print(f"{d2}, tablica 2wymiarowa\n")
print(f"{d3}, tablica 3wymiarowa\n")



<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(5,)
(2, 5)
(2, 2, 5), 

[1 2 3 4 5], tablica 1wymiarowa

[[1 2 3 4 5]
 [2 3 4 5 6]], tablica 2wymiarowa

[[[1 2 3 4 5]
  [6 2 3 4 5]]

 [[7 2 3 4 5]
  [8 2 3 4 5]]], tablica 3wymiarowa



In [3]:
d4 = np.array([range(5), range(1,6)])                                           # trzeba podac tyle samo elementow inaczej wyskakuje error ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

print(d4)

[[0 1 2 3 4]
 [1 2 3 4 5]]


In [4]:
d5 = np.arange(0, 10, 2)                                                        # start stop krok
print(d5)
# inna metoda
d55 = np.linspace(0, 10, 22)                                                    # od do ile elementow
print(d55)

d6 = np.zeros((2,2), dtype=int)                                                 # dtypy by default is float, similarily np.ones() create 1's
print(d6, d6.shape)

[0 2 4 6 8]
[ 0.          0.47619048  0.95238095  1.42857143  1.9047619   2.38095238
  2.85714286  3.33333333  3.80952381  4.28571429  4.76190476  5.23809524
  5.71428571  6.19047619  6.66666667  7.14285714  7.61904762  8.0952381
  8.57142857  9.04761905  9.52380952 10.        ]
[[0 0]
 [0 0]] (2, 2)


Indexing

In [5]:
print(d1)
print(d1[0], d1[1])                                                             # d1 is one dim array
print('\n')
print(d2)
print(d2[0,0], d2[0,1], d2[1,1], d2[1,2])                                       # d2 is two dim array, here we specify first index as row, second as column
print('\n')
print(d3)
print(d3[0,0,0], d3[1][0,0], d3[0,1,1], d3[1,1,1])                               # d3 is three dim array, here we specify first index as matrix, second as row, third as column, different formats accepted

[1 2 3 4 5]
1 2


[[1 2 3 4 5]
 [2 3 4 5 6]]
1 2 3 4


[[[1 2 3 4 5]
  [6 2 3 4 5]]

 [[7 2 3 4 5]
  [8 2 3 4 5]]]
1 7 2 2


Elements types

In [6]:
d3_float = d3.astype(float)
print(d3_float)

d3[1,1,1] = d3[1,1,1].astype(float)                                             # nie mozna zmienic typu per element, a przynajmniej zalozenie numpy jest aby cala macierz byla jednego typu danych
print(d3)

[[[1. 2. 3. 4. 5.]
  [6. 2. 3. 4. 5.]]

 [[7. 2. 3. 4. 5.]
  [8. 2. 3. 4. 5.]]]
[[[1 2 3 4 5]
  [6 2 3 4 5]]

 [[7 2 3 4 5]
  [8 2 3 4 5]]]


Nan and Inf

np.inf - jest floatem wiec jesli jego dodasz do tablicy to wszystkie elementy musza byc floatem

In [7]:
nums = np.array([0, 1, 2, np.nan, np.inf])
print(nums.dtype)

np.isnan(nums)
#np.isinf(nums)
np.isnan(nums).sum()

float64


1

# Statistical operations

**The median** is a measure of central tendency that represents the middle value in a sorted list of numbers. To find the median, you first need to arrange the numbers in ascending or descending order. If the list has an odd number of observations, the median is the number that is exactly in the middle of the list. If the list has an even number of observations, the median is the average of the two middle numbers.

**Standard deviation** is a statistical measure that quantifies the amount of variation or dispersion in a set of values. It is a widely used measure of the uncertainty or spread in a set of data. The standard deviation indicates how much the individual data points in a data set deviate from the mean (average) value of the set.

**Variance** is a statistical measure that represents the degree of spread in a set of data points. More specifically, it quantifies the average squared deviation of each number from the mean of the data set. Variance provides a way to quantify how much the numbers in the data set differ from each other and from the mean.

In [8]:
print(np.mean(d2), d2.mean())                                                   # dwa spososby
print(np.std(d2), d2.std())
print(np.var(d2), d2.var())
print(np.min(d2), d2.max())                                                     #
print(np.argmin(d2), d2.argmax())                                               # wszystkie te przyklady robia to na calej macierzy bez wzgledu na jej wymiar czyli biorą wsztstkie jej elementy

print(d2.mean(axis=0))                                                          # sredna po kolumnach
print(d2.mean(axis=1))                                                          # srednia po wierszach

3.5 3.5
1.5 1.5
2.25 2.25
1 6
0 9
[1.5 2.5 3.5 4.5 5.5]
[3. 4.]


# Reshaping arrays

In NumPy, the ***`shape`*** attribute of an array tells you the dimensions of the array (i.e., how many rows, columns, and so on), while the ***`reshape`*** method allows you to change the dimensions of the array without changing the data within it.

In NumPy, the ***`ravel`*** and ***`flatten`*** methods are used to convert a multi-dimensional array into a one-dimensional array. Both methods accomplish similar goals, but there are some differences in how they work and the results they produce.

The key difference between ravel and flatten is that ravel will return a view of the original array whenever possible (this means that changes to the result of ravel may also affect the original array), whereas flatten will always return a copy (changes to the result of flatten will not affect the original array).

In [9]:
print(d3.shape)
print(d3)
print(d3.reshape(4,5))                                                          # przeksztalcamy 3 wymiarowa w 2 wymiarowa, 4 wiersze 5 kolumn
print(d3.ravel())                                                               # przeksztalcamy 3 wymiarowa w 1 wymiarowa przeksztalcajac oryginal
print(d3.shape)
print(d3.flatten())                                                             # przeksztalcamy 3 wymiarowa w 1 wymiarowa tworzac nowa wynikowa i nie dotykajac oryginalu
print(d3.shape)
print(d3)



(2, 2, 5)
[[[1 2 3 4 5]
  [6 2 3 4 5]]

 [[7 2 3 4 5]
  [8 2 3 4 5]]]
[[1 2 3 4 5]
 [6 2 3 4 5]
 [7 2 3 4 5]
 [8 2 3 4 5]]
[1 2 3 4 5 6 2 3 4 5 7 2 3 4 5 8 2 3 4 5]
(2, 2, 5)
[1 2 3 4 5 6 2 3 4 5 7 2 3 4 5 8 2 3 4 5]
(2, 2, 5)
[[[1 2 3 4 5]
  [6 2 3 4 5]]

 [[7 2 3 4 5]
  [8 2 3 4 5]]]


# Sequence, repetitions, random numbers

In [10]:
a15 = np.arange(1,20,2)
print(a15)
a16 = np.repeat(a15,3)                                                          # repeat powiela kazdy element x razy i dalej nastepny element x razy itp, repeat robi tez automatycznie flatening ale mozna podac axis i wtedy zrobi jak trzeba
print(a16)
a17 = np.tile(a15,3)                                                            # tile powiela cala tablice x razy
print(a17)
from numpy import random
a18 = random.random((3,3,3))
print(a18)
a19 = random.randint(1,10, size=(3,3,3))                                         # od do ile elementow jaki rozmiar itp
print(a19)

[ 1  3  5  7  9 11 13 15 17 19]
[ 1  1  1  3  3  3  5  5  5  7  7  7  9  9  9 11 11 11 13 13 13 15 15 15
 17 17 17 19 19 19]
[ 1  3  5  7  9 11 13 15 17 19  1  3  5  7  9 11 13 15 17 19  1  3  5  7
  9 11 13 15 17 19]
[[[0.62298049 0.19303302 0.82064123]
  [0.41939988 0.00770983 0.00442721]
  [0.52741292 0.54168006 0.1659665 ]]

 [[0.45033963 0.31713959 0.90706867]
  [0.89203199 0.98454105 0.95234219]
  [0.34064766 0.37217337 0.48035185]]

 [[0.28980494 0.92619653 0.02776591]
  [0.42630471 0.11852853 0.09430062]
  [0.37284758 0.85397783 0.13299291]]]
[[[2 7 4]
  [9 3 4]
  [4 7 3]]

 [[1 6 1]
  [2 4 5]
  [4 9 1]]

 [[8 3 1]
  [1 8 2]
  [2 7 3]]]


# Where, argmax argmin

In [11]:
a20 = np.where(a19>3, a19, 0)
print(a20)
a20 = np.where(a19>3, a19, np.random.randint(100,110, size=(3,3,3)))
print(a20)

[[[0 7 4]
  [9 0 4]
  [4 7 0]]

 [[0 6 0]
  [0 4 5]
  [4 9 0]]

 [[8 0 0]
  [0 8 0]
  [0 7 0]]]
[[[107   7   4]
  [  9 103   4]
  [  4   7 104]]

 [[102   6 102]
  [108   4   5]
  [  4   9 107]]

 [[  8 102 101]
  [100   8 101]
  [103   7 106]]]


In [12]:
print(a20.max(), np.argmax(a20))
print(a20[:, 0])                                                # tylko pierwszy
print(a20[0, :])                                                # tylko pierwszy wiersz


108 12
[[107   7   4]
 [102   6 102]
 [  8 102 101]]
[[107   7   4]
 [  9 103   4]
 [  4   7 104]]


# File operations

In [13]:
np.save('a20.npy', a20)       #jakis format numpy
np.savetxt('a15.txt', a15)     #ale mozna tez format tekstowy tylko ze 1d albo 2d only, wiec a20 spadl i wzialem a15
                              # mozna zapisac 3d ale trzeba to rozbic na slicey czyli 2d i zapisac je jako osobne pliki, pozniej odpowiednio wczytujac

In [14]:
np.load('a20.npy')

array([[[107,   7,   4],
        [  9, 103,   4],
        [  4,   7, 104]],

       [[102,   6, 102],
        [108,   4,   5],
        [  4,   9, 107]],

       [[  8, 102, 101],
        [100,   8, 101],
        [103,   7, 106]]])

Concatenate, vstack, hstack, sort, argsort

In [22]:
b1 = np.array([1,2,3,4,5,6])
b2 = np.array([7,8,9,10,11,12])
b3 = np.concatenate((b1,b2))
b4 = np.vstack((b1,b2))
b5 = np.hstack((b1,b2))
print(b3, b5)
print(b4)

np.random.shuffle(b3)
print(b3)
b3 = np.sort(b3)
print(b3)




[ 1  2  3  4  5  6  7  8  9 10 11 12] [ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[ 1  7  6 12 11  4  9 10  8  2  3  5]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])